source 'https://rubygems.org'

# gem "rails"
gem 'activerecord', '~> 7.0', '>= 7.0.3.1'
gem 'faker'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rest-client'
gem 'erb-formatter'
gem 'shotgun'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.5'
gem 'uri', '~> 0.10.0'
gem 'net-http', '~> 0.2.2'
gem 'simplecov-erb', '~> 1.0'
